using TritStudio.Core;

internal static class Audit17Checks
{
    public static (string, Action)[] All =>
    [
        ("experimental initial memory does not include batch/sequence activations", () => {
            var r = LargeRequest(); r.ValidateInitialization(ModelConfig.Large);
            var estimate=TrainingMemoryEstimate.For(ModelConfig.Large,r,0);
            Check(estimate.ActivationBytes==0 && estimate.TotalBytes/1048576==694);
        }),
        ("legacy full CPU estimate reproduces owner 28342 MiB", () => {
            var r=LargeRequest();var e=TrainingMemoryEstimate.For(ModelConfig.Large,r,1024);
            Check(e.TotalBytes/1048576==28342);Throws<ArgumentException>(()=>r.Validate(ModelConfig.Large));
        }),
        ("actual short CPU batch is validated at actual length", () => {
            var r=LargeRequest();r.ValidateForTraining(ModelConfig.Large,453,false);
            Throws<ArgumentException>(()=>r.ValidateForTraining(ModelConfig.Large,1024,false));
        }),
        ("GPU activation estimate is not confused with host RAM quota", () => LargeRequest().ValidateForTraining(ModelConfig.Large,1024,true)),
        ("GPU still enforces persistent host planning envelope", () => Throws<ArgumentException>(()=>(LargeRequest() with {MemoryMiB=512}).ValidateForTraining(ModelConfig.Large,1024,true))),
        ("zero-step preflight is independent of batch and future length", () => {
            var a=TrainingMemoryEstimate.For(ModelConfig.Large,LargeRequest(),0);
            var b=TrainingMemoryEstimate.For(ModelConfig.Large,LargeRequest() with{BatchSize=1,SequenceLength=16},0);
            Check(a==b);
        }),
        ("creation still refuses an actually too-small persistent budget", () => Throws<ArgumentException>(()=>(LargeRequest() with{MemoryMiB=512}).ValidateInitialization(ModelConfig.Large))),
        ("training cannot use an effective length outside configured envelope", () => {
            Throws<ArgumentException>(()=>LargeRequest().ValidateForTraining(ModelConfig.Large,0,false));
            Throws<ArgumentException>(()=>(LargeRequest() with{SequenceLength=512}).ValidateForTraining(ModelConfig.Large,513,false));
        }),
        ("configuration errors remain errors in creation", () => {
            Throws<ArgumentException>(()=>(LargeRequest() with{BatchSize=65}).ValidateInitialization(ModelConfig.Large));
            Throws<ArgumentException>(()=>(LargeRequest() with{MemoryMiB=0}).ValidateInitialization(ModelConfig.Large));
            Throws<ArgumentException>(()=>(LargeRequest() with{SequenceLength=2048}).ValidateInitialization(ModelConfig.Large));
        }),
        ("activation planning remains monotone", () => {
            var r=LargeRequest();Check(TrainingMemoryEstimate.For(ModelConfig.Large,r,160).TotalBytes < TrainingMemoryEstimate.For(ModelConfig.Large,r,512).TotalBytes);
        }),
        ("memory error identifies configured RAM rather than free VRAM", () => {
            try {LargeRequest().ValidateForTraining(ModelConfig.Large,1024,false);}
            catch(ArgumentException e){Check(e.Message.Contains("RAM")&&e.Message.Contains("16")&&e.Message.Contains("VRAM"));return;}
            throw new Exception("Expected RAM refusal.");
        }),
        ("default learning rate is not the reported tiny 1e-6", () => Check(new TrainingOptions().LearningRate==.001)),
        ("learned Python fixture is generated by real CPU inference, not a text table", () => {
            string file=Path.Combine(AppContext.BaseDirectory,"learning-reference.tritmodel");
            Check(ModelFiles.Hash(file).Equals("f48e827aad3af94c2c6395b55991000e617db21b82c2bfcc6d69e41b4536e697",StringComparison.OrdinalIgnoreCase));
            var model=new ManagedInference(ModelFiles.Read(file,true),0,1);
            foreach(var pair in new[]{("Привет!","Привет!"),("Как дела?","Хорошо."),("Как тебя зовут?","Трит."),("Спасибо.","Пожалуйста."),("Пока!","До встречи!"),("Ты тут?","Да.")})
            {
                string actual=model.Generate(ByteTokenizer.Prompt([],pair.Item1,model.Weights.Config.Context,64),()=>new SamplingOptions(0,262,1,1,64),null,CancellationToken.None);
                if(actual!=pair.Item2)throw new Exception($"Learned fixture recall failed: {pair.Item1} -> {actual}");
            }
        }),
        ("only explicit learned test fixture enters small app update", () => {
            Check(UpdatePayloadPolicy.IsOwnedPayload("checks/learning-reference.tritmodel"));
            Check(!UpdatePayloadPolicy.IsOwnedPayload("checks/my-private-model.tritmodel"));
        }),
    ];
    private static ResourceOptions LargeRequest()=>new(){MemoryMiB=16384,BatchSize=32,SequenceLength=1024,PreferCuda=false};
    private static void Check(bool value){if(!value)throw new Exception("audit17 contract failed");}
    private static void Throws<T>(Action action) where T:Exception {try{action();}catch(T){return;}throw new Exception("Expected "+typeof(T).Name);}
}
